import discord, random
import discord.ext.commands as client
from discord.ext.commands.cooldowns import BucketType


class Gays(client.Cog):

    def __init__(self, bot):
         self.bot = bot

    @client.command(pass_context=True, aliases=['gay'])
    @client.cooldown(1, 2, BucketType.user)
    async def gays(self, ctx):
        responses = [
            "You're 1% Gay.",
            "You're 2% Gay.", 
            "You're 3% Gay.",
            "You're 4% Gay.", 
            "You're 5% Gay.",
            "You're 6% Gay.", 
            "You're 7% Gay.", 
            "You're 8% Gay.", 
            "You're 9% Gay.", 
            "You're 10% Gay.",
            "You're 11% Gay.",
            "You're 12% Gay.",
            "You're 13% Gay.",
            "You're 14% Gay.", 
            "You're 15% Gay.",
            "You're 16% Gay.", 
            "You're 17% Gay.",
            "You're 18% Gay.", 
            "You're 19% Gay.", 
            "You're 20% Gay.", 
            "You're 21% Gay.", 
            "You're 22% Gay.",
            "You're 23% Gay.",
            "You're 24% Gay.",
            "You're 25% Gay.",
            "You're 26% Gay.", 
            "You're 27% Gay.",
            "You're 28% Gay.", 
            "You're 29% Gay.",
            "You're 30% Gay.", 
            "You're 31% Gay.", 
            "You're 32% Gay.", 
            "You're 33% Gay.", 
            "You're 34% Gay.",
            "You're 35% Gay.",
            "You're 36% Gay.",
            "You're 37% Gay.",
            "You're 38% Gay.", 
            "You're 39% Gay.",
            "You're 40% Gay.", 
            "You're 41% Gay.",
            "You're 42% Gay.", 
            "You're 43% Gay.", 
            "You're 44% Gay.", 
            "You're 45% Gay.", 
            "You're 46% Gay.",
            "You're 47% Gay.",
            "You're 48% Gay.",
            "You're 49% Gay.",
            "You're 50% Gay.", 
            "You're 51% Gay.",
            "You're 52% Gay.", 
            "You're 53% Gay.",
            "You're 54% Gay.", 
            "You're 55% Gay.", 
            "You're 56% Gay.", 
            "You're 57% Gay.", 
            "You're 58% Gay.",
            "You're 59% Gay.",
            "You're 60% Gay.",
            "You're 61% Gay.",
            "You're 62% Gay.", 
            "You're 63% Gay.",
            "You're 64% Gay.", 
            "You're 65% Gay.",
            "You're 66% Gay.", 
            "You're 67% Gay.", 
            "You're 68% Gay.", 
            "You're 69% Gay ||nice.||", 
            "You're 70% Gay.",
            "You're 71% Gay.",
            "You're 72% Gay.",
            "You're 73% Gay.",
            "You're 74% Gay.", 
            "You're 75% Gay.", 
            "You're 76% Gay.", 
            "You're 77% Gay.",
            "You're 78% Gay.",
            "You're 79% Gay.",
            "You're 80% Gay.",
            "You're 81% Gay.", 
            "You're 82% Gay.",
            "You're 83% Gay.", 
            "You're 84% Gay.",
            "You're 85% Gay.", 
            "You're 86% Gay.", 
            "You're 87% Gay.", 
            "You're 88% Gay.", 
            "You're 89% Gay.",
            "You're 90% Gay.",
            "You're 91% Gay.",
            "You're 92% Gay.", 
            "You're 93% Gay.",
            "You're 94% Gay.",
            "You're 95% Gay.", 
            "You're 96% Gay.", 
            "You're 97% Gay.", 
            "You're 98% Gay.", 
            "You're 99% Gay.",
            "You're 100% Gay.🏳️‍🌈",
            "Nah, you're good.",
            "You're 10000000% Gay.🏳️‍🌈",
            "You're 0% Gay, good for you."
        ]
        await ctx.send(f"{random.choice(responses)}")
        print(ctx)

def setup(bot):
    bot.add_cog(Gays(bot))
