import discord, random
import discord.ext.commands as client
from discord.ext.commands.cooldowns import BucketType


class IQ(client.Cog):

    def __init__(self, bot):
         self.bot = bot

    @client.command(aliases=["IQ", "Iq"])
    @client.cooldown(1, 2, BucketType.user)
    async def iq(self, ctx):
        responses = [
"Your IQ is 0 ||Literally no brain||",
"Your IQ is 1 ||No brain||",
"Your IQ is 2 ||No brain||", 
"Your IQ is 3 ||No brain||",
"Your IQ is 4 ||No brain||",
"Your IQ is 5 ||No brain||",
"Your IQ is 6 ||No brain||",
"Your IQ is 7 ||No brain||", 
"Your IQ is 8 ||No brain||",
"Your IQ is 9 ||No brain||",
"Your IQ is 10 ||No brain||",
"Your IQ is 11 ||No brain||",
"Your IQ is 12 ||No brain||", 
"Your IQ is 13 ||No brain||",
"Your IQ is 14 ||No brain||",
"Your IQ is 15 ||No brain||",
"Your IQ is 16 ||No brain||",
"Your IQ is 17 ||No brain||", 
"Your IQ is 18 ||No brain||",
"Your IQ is 19 ||No brain||",
"Your IQ is 20 ||No brain||",
"Your IQ is 21 ||Monkey brain||",
"Your IQ is 22 ||Monkey brain||", 
"Your IQ is 23 ||Monkey brain||",
"Your IQ is 24 ||Monkey brain||",
"Your IQ is 25 ||Monkey brain||",
"Your IQ is 26 ||Monkey brain||",
"Your IQ is 27 ||Monkey brain||", 
"Your IQ is 28 ||Monkey brain||",
"Your IQ is 29 ||Monkey brain||",
"Your IQ is 30 ||Monkey brain||",
"Your IQ is 31 ||Smol brain||",
"Your IQ is 32 ||Smol brain||", 
"Your IQ is 33 ||Smol brain||",
"Your IQ is 34 ||Smol brain||",
"Your IQ is 35 ||Smol brain||",
"Your IQ is 36 ||Smol brain||",
"Your IQ is 37 ||Smol brain||",
"Your IQ is 38 ||Smol brain||",
"Your IQ is 39 ||Smol brain||",
"Your IQ is 40 ||Smol brain||",
"Your IQ is 41 ||Smol brain||",
"Your IQ is 42 ||Smol brain||",
"Your IQ is 43 ||Smol brain||",
"Your IQ is 44 ||Smol brain||",
"Your IQ is 45 ||Smol brain||",
"Your IQ is 46 ||Smol brain||",
"Your IQ is 47 ||Smol brain||",
"Your IQ is 48 ||Smol brain||",
"Your IQ is 49 ||Smol brain||",
"Your IQ is 50 ||At least a human||",
"Your IQ is 51 ||At least a human||",
"Your IQ is 52 ||At least a human||",
"Your IQ is 53 ||At least a human||",
"Your IQ is 54 ||At least a human||",
"Your IQ is 55 ||At least a human||",
"Your IQ is 56 ||At least a human||",
"Your IQ is 57 ||At least a human||",
"Your IQ is 58 ||At least a human||",
"Your IQ is 59 ||At least a human||",
"Your IQ is 60 ||At least a human||",
"Your IQ is 61 ||At least a human||",
"Your IQ is 62 ||At least a human||",
"Your IQ is 63 ||At least a human||",
"Your IQ is 64 ||At least a human||",
"Your IQ is 65 ||At least a human||",
"Your IQ is 66 ||At least a human||",
"Your IQ is 67 ||At least a human||",
"Your IQ is 68 ||At least a human||",
"Your IQ is 69 ||Nice||",
"Your IQ is 70  ||Not bad||",
"Your IQ is 71 ||Not bad||",
"Your IQ is 72 ||Not bad||", 
"Your IQ is 73 ||Not bad||",
"Your IQ is 74 ||Not bad||",
"Your IQ is 75 ||Not bad||",
"Your IQ is 76 ||Not bad||",
"Your IQ is 77 ||Not bad||", 
"Your IQ is 78 ||Not bad||",
"Your IQ is 79 ||Not bad||",
"Your IQ is 80 ||Not bad||",
"Your IQ is 81 ||Not bad||",
"Your IQ is 82 ||Not bad||", 
"Your IQ is 83 ||Not bad||",
"Your IQ is 84 ||Not bad||",
"Your IQ is 85 ||Not bad||",
"Your IQ is 86 ||Not bad||",
"Your IQ is 87 ||Not bad||", 
"Your IQ is 88 ||Not bad||",
"Your IQ is 89 ||Not bad||",
"Your IQ is 90 ||G00d||",
"Your IQ is 91 ||G00d||",
"Your IQ is 92 ||G00d||", 
"Your IQ is 93 ||G00d||",
"Your IQ is 94 ||G00d||",
"Your IQ is 95 ||G00d||",
"Your IQ is 96 ||G00d||",
"Your IQ is 97 ||G00d||", 
"Your IQ is 98 ||G00d||",
"Your IQ is 99 ||G00d||",
"Your IQ is 100 ||G00d||",
"Your IQ is 101 ||G00d||",
"Your IQ is 102 ||G00d||", 
"Your IQ is 103 ||G00d||",
"Your IQ is 104 ||G00d||",
"Your IQ is 105 ||Smart||",
"Your IQ is 106 ||Smart||",
"Your IQ is 107 ||Smart||", 
"Your IQ is 108 ||Smart||",
"Your IQ is 109 ||Smart||",
"Your IQ is 110 ||Smart||",
"Your IQ is 111 ||Smart||",
"Your IQ is 112 ||Smart||", 
"Your IQ is 113 ||Smart||",
"Your IQ is 114 ||Smart||",
"Your IQ is 115 ||Smart||",
"Your IQ is 116 ||Smart||",
"Your IQ is 117 ||Smart||", 
"Your IQ is 118 ||Smart||",
"Your IQ is 119 ||Smart||",
"Your IQ is 120 ||Smart ass||",
"Your IQ is 121 ||Smart ass||",
"Your IQ is 122 ||Smart ass||", 
"Your IQ is 123 ||Smart ass||",
"Your IQ is 124 ||Smart ass||",
"Your IQ is 125 ||Smart ass||",
"Your IQ is 126 ||Smart ass||",
"Your IQ is 127 ||Smart ass||", 
"Your IQ is 128 ||Smart ass||",
"Your IQ is 129 ||Smart ass||",
"Your IQ is 130 ||Smart ass||",
"Your IQ is 131 ||Smart ass||",
"Your IQ is 132 ||Smart ass||", 
"Your IQ is 133 ||Smart ass||",
"Your IQ is 134 ||Smart ass||",
"Your IQ is 135 ||Smart ass||",
"Your IQ is 136 ||Smart ass||",
"Your IQ is 137 ||Smart ass||", 
"Your IQ is 138 ||Smart ass||",
"Your IQ is 139 ||Smart ass||",
"Your IQ is 140 ||Smart ass||",
"Your IQ is 141 ||Smart ass||",
"Your IQ is 142 ||Smart ass||", 
"Your IQ is 143 ||Smart ass||",
"Your IQ is 144 ||Smart ass||",
"Your IQ is 145 ||Smart ass||",
"Your IQ is 146 ||Smart ass||",
"Your IQ is 147 ||Smart ass||", 
"Your IQ is 148 ||Smart ass||",
"Your IQ is 149 ||Smart ass||",
"Your IQ is 150 ||Smart ass||",
"Your IQ is 151 ||Too cool for school||",
"Your IQ is 152 ||Too cool for school||", 
"Your IQ is 153 ||Too cool for school||",
"Your IQ is 154 ||Too cool for school||",
"Your IQ is 155 ||Too cool for school||",
"Your IQ is 156 ||Too cool for school||",
"Your IQ is 157 ||Too cool for school||", 
"Your IQ is 158 ||Too cool for school||",
"Your IQ is 159 ||Too cool for school||",
"Your IQ is 160 ||Too cool for school||",
"Your IQ is 161 ||Too cool for school||",
"Your IQ is 162 ||Too cool for school||", 
"Your IQ is 163 ||Too cool for school||",
"Your IQ is 164 ||Too cool for school||",
"Your IQ is 165 ||Too cool for school||",
"Your IQ is 166 ||Too cool for school||",
"Your IQ is 167 ||Too cool for school||", 
"Your IQ is 168 ||Too cool for school||",
"Your IQ is 169 ||Too nice for school||",
"Your IQ is 170 ||Too cool for school||",
"Your IQ is 171 ||Too cool for school||",
"Your IQ is 172 ||Too cool for school||", 
"Your IQ is 173 ||Too cool for school||",
"Your IQ is 174 ||Too cool for school||",
"Your IQ is 175 ||Too cool for school||",
"Your IQ is 176 ||Too cool for school||",
"Your IQ is 177 ||Too cool for school||", 
"Your IQ is 178 ||Too cool for school||",
"Your IQ is 179 ||Too cool for school||",
"Your IQ is 180 ||Too cool for school||",
"Your IQ is 181 ||BIG BRAIN||",
"Your IQ is 182 ||BIG BRAIN||", 
"Your IQ is 183 ||BIG BRAIN||",
"Your IQ is 184 ||BIG BRAIN||",
"Your IQ is 185 ||BIG BRAIN||",
"Your IQ is 186 ||BIG BRAIN||",
"Your IQ is 187 ||BIG BRAIN||", 
"Your IQ is 188 ||BIG BRAIN||",
"Your IQ is 189 ||BIG BRAIN||",
"Your IQ is 190 ||BIG BRAIN||",
"Your IQ is 191 ||BIG BRAIN||",
"Your IQ is 192 ||BIG BRAIN||", 
"Your IQ is 193 ||BIG BRAIN||",
"Your IQ is 194 ||BIG BRAIN||",
"Your IQ is 195 ||**MASSIVE BRAIN**||",
"Your IQ is 196 ||**MASSIVE BRAIN**||",
"Your IQ is 197 ||**MASSIVE BRAIN**||", 
"Your IQ is 198 ||**MASSIVE BRAIN**||",
"Your IQ is 199 ||**MASSIVE BRAIN**||",
"Your IQ is 200 ||**MASSIVE BRAIN**||",
"Your IQ is 201 ||**MASSIVE BRAIN**||",
"Your IQ is 202 ||**MASSIVE BRAIN**||", 
"Your IQ is 203 ||**MASSIVE BRAIN**||",
"Your IQ is 204 ||**MASSIVE BRAIN**||",
"Your IQ is 205 ||**MASSIVE BRAIN**||",
"Your IQ is 206 ||**MASSIVE BRAIN**||",
"Your IQ is 207 ||**MASSIVE BRAIN**||", 
"Your IQ is 208 ||**MASSIVE BRAIN**||",
"Your IQ is 209 ||**MASSIVE BRAIN**||",
"Your IQ is 210 ||**MASSIVE BRAIN**||",
"Your IQ is 211 ||**MASSIVE BRAIN**||",
"Your IQ is 212 ||**MASSIVE BRAIN**||", 
"Your IQ is 213 ||**MASSIVE BRAIN**||",
"Your IQ is 214 ||**MASSIVE BRAIN**||",
"Your IQ is 215 ||**MASSIVE BRAIN**||",
"Your IQ is 216 ||**MASSIVE BRAIN**||",
"Your IQ is 217 ||**MASSIVE BRAIN**||", 
"Your IQ is 218 ||**MASSIVE BRAIN**||",
"Your IQ is 219 ||**MASSIVE BRAIN**||",
"Your IQ is 220 ||**MASSIVE BRAIN**||",
"Your IQ is 221 ||Alien||",
"Your IQ is 222 ||Alien||", 
"Your IQ is 223 ||Alien||",
"Your IQ is 224 ||Alien||",
"Your IQ is 225 ||Alien||",
"Your IQ is 226 ||Alien||",
"Your IQ is 227 ||Alien||",
"Your IQ is 228 ||Alien||", 
"Your IQ is -1",
"Your IQ is -2",
"Your IQ is -3",
"Your IQ is -4",
"Your IQ is -5", 
"Your IQ is -6",
"Your IQ is -7",
"Your IQ is -8",
"Your IQ is -9",
"Your IQ is -10", 
"Your IQ is -11",
"Your IQ is -12",
"Your IQ is -13",
"Your IQ is -14",
"Your IQ is -15", 
"Your IQ is -16",
"Your IQ is -17", 
"Your IQ is -18",
"Your IQ is -19",
"Your IQ is -20",
"Your IQ is -21",
"Your IQ is -22", 
"Your IQ is -23",
"Your IQ is -24",
"Your IQ is -25",
"Your IQ is -26",
"Your IQ is -27", 
"Your IQ is -28",
"Your IQ is -29",
"Your IQ is -30",
"Your IQ is -31",
"Your IQ is -32", 
"Your IQ is -33",
"Your IQ is -34",
"Your IQ is -35",
"Your IQ is -36",
"Your IQ is -37",
"Your IQ is -38",
"Your IQ is -39",
"Your IQ is -40",
"Your IQ is -41",
"Your IQ is -42",
"Your IQ is -43",
"Your IQ is -44",
"Your IQ is -45",
"Your IQ is -46",
"Your IQ is -47",
"Your IQ is 48",
"Your IQ is -49",
"Your IQ is -50",
"Your IQ is -51",
"Your IQ is -52",
"Your IQ is -53",
"Your IQ is -54",
"Your IQ is -55",
"Your IQ is -56",
"Your IQ is -57",
"Your IQ is -58",
"Your IQ is -59",
"Your IQ is -60",
"Your IQ is -61",
"Your IQ is -62",
"Your IQ is -63",
"Your IQ is -64",
"Your IQ is -65",
"Your IQ is -66",
"Your IQ is -67",
"Your IQ is -68",
"Your IQ is -69",
"Your IQ is -70",
"Your IQ is -71",
"Your IQ is -72", 
"Your IQ is -73",
"Your IQ is -74",
"Your IQ is -75",
"Your IQ is -76",
"Your IQ is -77", 
"Your IQ is -78",
"Your IQ is -79",
"Your IQ is -80",
"Your IQ is -81",
"Your IQ is -82", 
"Your IQ is -83",
"Your IQ is -84",
"Your IQ is -85",
"Your IQ is -86",
"Your IQ is -87", 
"Your IQ is -88",
"Your IQ is -89",
"Your IQ is -90",
"Your IQ is -91",
"Your IQ is -92", 
"Your IQ is -93",
"Your IQ is -94",
"Your IQ is -95",
"Your IQ is -96",
"Your IQ is -97", 
"Your IQ is -98",
"Your IQ is -99",
"Your IQ is -100",
"Your IQ is -101",
"Your IQ is -102", 
"Your IQ is -103",
"Your IQ is -104",
"Your IQ is -105",
"Your IQ is -106",
"Your IQ is -107", 
"Your IQ is -108",
"Your IQ is -109",
"Your IQ is -110",
"Your IQ is -111",
"Your IQ is -112", 
"Your IQ is -113",
"Your IQ is -114",
"Your IQ is -115",
"Your IQ is -116",
"Your IQ is -117", 
"Your IQ is -118",
"Your IQ is -119",
"Your IQ is -120",
"Your IQ is -121",
"Your IQ is -122", 
"Your IQ is -123",
"Your IQ is -124",
"Your IQ is -125",
"Your IQ is -126",
"Your IQ is -127", 
"Your IQ is -128",
"Your IQ is -129",
"Your IQ is -130",
"Your IQ is -131",
"Your IQ is -132", 
"Your IQ is -133",
"Your IQ is -134",
"Your IQ is -135",
"Your IQ is -136",
"Your IQ is -137", 
"Your IQ is -138",
"Your IQ is -139",
"Your IQ is -140",
"Your IQ is -141",
"Your IQ is -142", 
"Your IQ is -143",
"Your IQ is -144",
"Your IQ is -145",
"Your IQ is -146",
"Your IQ is -147", 
"Your IQ is -148",
"Your IQ is -149",
"Your IQ is -150",
"Your IQ is -151",
"Your IQ is -152", 
"Your IQ is -153",
"Your IQ is -154",
"Your IQ is -155",
"Your IQ is -156",
"Your IQ is -157", 
"Your IQ is -158",
"Your IQ is -159",
"Your IQ is -160",
"Your IQ is -161",
"Your IQ is -162", 
"Your IQ is -163",
"Your IQ is -164",
"Your IQ is -165",
"Your IQ is -166",
"Your IQ is -167", 
"Your IQ is -168",
"Your IQ is -169",
"Your IQ is -170",
"Your IQ is -171",
"Your IQ is -172", 
"Your IQ is -173",
"Your IQ is -174",
"Your IQ is -175",
"Your IQ is -176",
"Your IQ is -177", 
"Your IQ is -178",
"Your IQ is -179",
"Your IQ is -180",
"Your IQ is -181",
"Your IQ is -182", 
"Your IQ is -183",
"Your IQ is -184",
"Your IQ is -185",
"Your IQ is -186",
"Your IQ is -187", 
"Your IQ is -188",
"Your IQ is -189",
"Your IQ is -190",
"Your IQ is -191",
"Your IQ is -192", 
"Your IQ is -193",
"Your IQ is -194",
"Your IQ is -195",
"Your IQ is -196",
"Your IQ is -197", 
"Your IQ is -198",
"Your IQ is -199",
"Your IQ is -200",
"Your IQ is -201",
"Your IQ is -202", 
"Your IQ is -203",
"Your IQ is -204",
"Your IQ is -205",
"Your IQ is -206",
"Your IQ is -207", 
"Your IQ is -208",
"Your IQ is -209",
"Your IQ is -210",
"Your IQ is -211",
"Your IQ is -212", 
"Your IQ is -213",
"Your IQ is -214",
"Your IQ is -215",
"Your IQ is -216",
"Your IQ is -217", 
"Your IQ is -218",
"Your IQ is -219",
"Your IQ is -220",
"Your IQ is -221",
"Your IQ is -222", 
"Your IQ is -223",
"Your IQ is -224",
"Your IQ is -225",
"Your IQ is -226",
"Your IQ is -227",
"Your IQ is -228",
"Your IQ is ||Not too high||",
"Your IQ is ||Gay||", 
"Your IQ is ||g0oD||",
"Your IQ is ||Too high||",
"Your IQ is ||I dunno||",
"Your IQ is ||Smarter than a monkey||",
"Your IQ is 999999 ||GODLY||",
"Your IQ is -999999 ||**E̶͔̝̥̼̥̋̇͂̒̎͂͗̈́͑Ą̷̛̗̻͓̩̮̇͛̈́̏̉̔͗̋Ŕ̸̟̙̟̠̱͎͖̳̾͠͝͝Ţ̵̜̹̹̼̗̜̣̝͒̎̾̊̕͝Ḩ̴̥͇͉͎̰͇͂͗̈̔͊̿̍͝ ̴̫͔̙͈̼̈̕W̶̧̧͇͍̭̦̭̉͋̚͠I̷̡͎͉͇̻̠͑͋̃̈́̃L̴̨̟̻̟̊́̊̊̈̀̏͝L̶͈̩̓̈̀̊̈́͊̂̅͂ ̴̲͓̬͙͎̹̖̂̇̃̑̓̅̀̚͜͝B̴̛̬͓̥̈̆̀̍̀͌́͝Ḙ̶̲̆̔͊͛̎̄͗̕͘ ̴̡̪͔͎͈͉̓̾͗̀̈̂̒͜͠ͅD̴̘̹̹͉̲̃̄̀͠ͅĒ̴̯͍̜͎̞̥̃̈́̾̃̊͊͝͠ͅͅŜ̶̱̱̓̃̔̈̑͑̂͝T̴̺͍͔͚͍͋̾͝ͅR̸̨̛͙̹͙̮̣̝̘̙͋̊̏̎̅̎͝Ơ̸̧͓̱̣̹͚̣̏Y̷̨̨̙͉͚̻̞̟̜͑̉͗̓͒͠Ȩ̸̡̧̫̺̽̿̌͛͘͝ͅD̵͔̉ ̶̻̮͔̠́̏̀̄̀B̴̙̘͕̯̘̎͛̒Y̵͇̐̋̏̎̈́̋͂̋͝ ̶̙̩̦̼̗̊̂͋͊͐̀͜Y̷̡̙͓̤̲̍̈̏͗̌́̕͘͠O̷̢̨̩̭̪̦̒͐͆͜Ů̸̡͖̙͓̦͎̉̓̒̅͆ͅR̵̹̰̈́͜ͅ ̷̰̩̫̞̑̋S̵̗̼̰͐́̂̃Ţ̴̢̹̗͚̠͙̯͒̔̏͗́Ư̷̭̥̣̘͗̂̿̍̀P̵̭͑̀̃Į̸̢̥̣̳̗̻̼̻̽̀̒̄̃̑͝͝D̵͎̬̠͚͆̍͛͆͆̊̂͜Ȋ̶͇̺̙͔̙̻͔̏̌̀T̸̥̰̳̞̭̆̓̓̉͛̕͝͝͠Y̴̢͉̜̮̟̍̈̍̈́**||"
        ]
        await ctx.send(f"{random.choice(responses)}")

def setup(bot):
    bot.add_cog(IQ(bot))
